// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRelszAJiVCrSfUwM8F5oWSJ8JRBR722Q',
    appId: '1:949834315205:web:ab484806284e933b4247ac',
    messagingSenderId: '949834315205',
    projectId: 'projetoteste-adfa9',
    authDomain: 'projetoteste-adfa9.firebaseapp.com',
    storageBucket: 'projetoteste-adfa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GyruxKw0oqDUDkZ4IlPMbwtW9TRpn2I',
    appId: '1:949834315205:android:928876ba144f40bd4247ac',
    messagingSenderId: '949834315205',
    projectId: 'projetoteste-adfa9',
    storageBucket: 'projetoteste-adfa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOjA0krRJQr5lqk6hdIx-HdNYRYRC4fg',
    appId: '1:949834315205:ios:adf4e114b710cf354247ac',
    messagingSenderId: '949834315205',
    projectId: 'projetoteste-adfa9',
    storageBucket: 'projetoteste-adfa9.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOjA0krRJQr5lqk6hdIx-HdNYRYRC4fg',
    appId: '1:949834315205:ios:adf4e114b710cf354247ac',
    messagingSenderId: '949834315205',
    projectId: 'projetoteste-adfa9',
    storageBucket: 'projetoteste-adfa9.firebasestorage.app',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRelszAJiVCrSfUwM8F5oWSJ8JRBR722Q',
    appId: '1:949834315205:web:f0b5c39d4640bf084247ac',
    messagingSenderId: '949834315205',
    projectId: 'projetoteste-adfa9',
    authDomain: 'projetoteste-adfa9.firebaseapp.com',
    storageBucket: 'projetoteste-adfa9.firebasestorage.app',
  );
}
